services:
  gin-mall:
    container_name: gin-mall
    image: gin-mall:v1.0
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - my_net
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=miyike3716
      - MYSQL_DATABASE=golang_mall_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_net

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "miyike3716"]
    restart: always
    networks:
      - my_net

volumes:
  mysql_data:
networks:
  my_net:
